[project]
protostar-version = "0.9.1"
lib-path = "lib"
cairo-path = [
    "./lib/cairo_contracts/src",
    "src",
]

[contracts]
ERC3525MintableBurnable = ["./src/carbonable/erc3525/presets/ERC3525MintableBurnable.cairo"]
ERC3525SlotApprovable = ["./src/carbonable/erc3525/presets/ERC3525SlotApprovable.cairo"]
ERC3525SlotEnumerableMintableBurnable = ["./src/carbonable/erc3525/presets/ERC3525SlotEnumerableMintableBurnable.cairo"]

[profile.testnet.project]
network="testnet"
private-key-path = "./.env"
account-address="0x03F878C94De81906ba1A016aB0E228D361753536681a776ddA29674FfeBB3CB0"